# Generated by Django 2.1.5 on 2019-09-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20190901_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(default='stuff', unique=True),
            preserve_default=False,
        ),
    ]
